title: Default Page
options:
  changeSlug: false
  delete: false
columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          text:
            type: textarea
            size: huge
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        template: associations
      files:
        type: files
